name: drink
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.9
  path_provider: ^2.0.11
  flutter_speed_dial: ^6.2.0
  dropdown_cupertino: ^0.0.8
  flutter_animate: ^3.0.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/2beerIcon.png"

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/2beer.png
    - assets/images/beer.png
    - assets/images/beer2.png
    - assets/images/beer3.png
    - assets/images/beer3p.png
    - assets/images/tag.png
    - assets/images/tagf.png
    - assets/images/tags.png
    - assets/default.json
    - assets/lang.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: McLaren
      fonts:
        - asset: assets/fonts/McLaren-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_native_splash:
  color: "#5DCA7C"
  image: "assets/images/2beerIcon.png"

  android_12:
    image: "assets/images/2beerIcon.png"
    color: "#5DCA7C"